package com.fran.teclas.keyboard.unified

import java.io.BufferedReader
import java.io.InputStream

/**
 * The contextual language-model leg of the score fusion: a compact on-device bigram model giving
 * the relative strength with which the LANGUAGE (not just this user) continues `prev` with `word`.
 * This is what lets "I am going to the ___" prefer "store" over "stork" even when the user has
 * never typed either — the personal n-gram store only knows words the user has already used.
 *
 * Format (one bigram per line, '#' comments allowed):  `prev word count`
 * Counts are arbitrary positive integers — probabilities are normalized per-prev at load, so any
 * corpus scale works. The shipped seed is generated by tools/lm/build_bigrams.py and can be
 * regenerated from any corpus without touching this class.
 *
 * Memory: a few thousand bigrams ≈ tens of KB. Lookup is two map reads — microseconds, safe on
 * every ranking pass. Loading happens once, off the main thread, AFTER the keyboard is visible
 * (see hosts) so cold-open cost stays zero; until then [prob] returns 0 and the ranker simply
 * runs without the LM signal, exactly as it did before this leg existed.
 */
class ContextModel {

    // prev → (word → relative strength 0..1, normalized to the strongest continuation of prev).
    @Volatile private var bigrams: Map<String, Map<String, Float>> = emptyMap()

    val isLoaded: Boolean get() = bigrams.isNotEmpty()

    /** Relative continuation strength of `prev word` (0 when unknown or model not yet loaded). */
    fun prob(prev: String, word: String): Float =
        bigrams[prev.lowercase()]?.get(word.lowercase()) ?: 0f

    /** The language's strongest continuations of [prev], best-first — blended into the
     *  between-words prediction strip after the user's own n-gram habits. */
    fun topContinuations(prev: String, limit: Int = 3): List<String> =
        bigrams[prev.lowercase()]?.entries
            ?.sortedByDescending { it.value }
            ?.take(limit)
            ?.map { it.key }
            ?: emptyList()

    /** Parse and swap in a bigram table. Call from a background thread; reads are lock-free. */
    fun load(stream: InputStream) {
        val counts = HashMap<String, HashMap<String, Float>>()
        stream.bufferedReader().use { r: BufferedReader ->
            r.forEachLine { line ->
                if (line.isEmpty() || line.startsWith("#")) return@forEachLine
                val parts = line.split(' ')
                if (parts.size != 3) return@forEachLine
                val n = parts[2].toFloatOrNull() ?: return@forEachLine
                if (n <= 0f) return@forEachLine
                counts.getOrPut(parts[0].lowercase()) { HashMap() }[parts[1].lowercase()] = n
            }
        }
        // Normalize each prev's continuations to its strongest one → 0..1 relative strengths.
        counts.values.forEach { m ->
            val max = m.values.max()
            if (max > 0f) m.entries.forEach { it.setValue(it.value / max) }
        }
        bigrams = counts
    }
}
